---
# noqa: var-naming[no-role-prefix]

foreman_products_defaults: &foreman_products_defaults
  content_type: yum
  gpg_key: "{{ foreman_cred_name_prefix | default('') }}RPM-GPG-KEY-Hashicorp"
  download_policy: "{{ foreman_products_defaults_download_policy_hashicorp }}"
  # mirror_on_sync: True
  # mirroring_policy: "additive"
  # mirroring_policy: "mirror_content_only"
  # mirroring_policy: "mirror_complete"
  mirroring_policy: "{{ foreman_products_defaults_mirroring_policy_hashicorp }}"
  verify_ssl_on_sync: "{{ foreman_products_defaults_verify_ssl_on_sync_hashicorp | bool }}"
  # http_proxy: Default Proxy
  http_proxy_policy: "{{ foreman_products_defaults_http_proxy_policy_hashicorp }}"
  unprotected: "{{ foreman_products_defaults_unprotected_hashicorp | bool }}"

foreman_products_defaults_debian: &foreman_products_defaults_debian
  <<: *foreman_products_defaults
  content_type: deb
  # deb_releases: stable
  deb_components: main
  deb_architectures: amd64

foreman_products_hashicorp_el7:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - RHEL 7"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-el7"
        url: "{{ foreman_repo_baseurl_hashicorp_rpm }}/RHEL/7/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_el7 }}"

foreman_products_hashicorp_el8:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - RHEL 8"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-el8"
        url: "{{ foreman_repo_baseurl_hashicorp_rpm }}/RHEL/8/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_el8 }}"

foreman_products_hashicorp_el9:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - RHEL 9"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-el9"
        url: "{{ foreman_repo_baseurl_hashicorp_rpm }}/RHEL/9/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_el9 }}"


foreman_products_hashicorp_fedora37:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_fedora37 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - Fedora 37"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-fedora37"
        url: "{{ foreman_repo_baseurl_hashicorp }}/RHEL/7/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_fedora37 }}"

foreman_products_hashicorp_fedora38:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_fedora38 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - Fedora 38"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-fedora38"
        url: "{{ foreman_repo_baseurl_hashicorp }}/RHEL/8/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_fedora38 }}"

foreman_products_hashicorp_fedora39:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_fedora39 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - Fedora 39"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-fedora39"
        url: "{{ foreman_repo_baseurl_hashicorp }}/RHEL/9/x86_64/stable"
        <<: *foreman_products_defaults
        organization: "{{ foreman_organization_hashicorp_fedora39 }}"


foreman_products_hashicorp_debian9:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 9 (Stretch)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-debian9"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_debian9 }}"
        deb_releases: stretch

foreman_products_hashicorp_debian10:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 10 (Buster)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-debian10"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_debian10 }}"
        deb_releases: buster

foreman_products_hashicorp_debian11:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_debian11 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 11 (Bullseye)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-debian11"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_debian11 }}"
        deb_releases: bullseye

foreman_products_hashicorp_debian12:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_debian12 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 12 (Bookworm)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-debian12"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_debian12 }}"
        deb_releases: bookworm


foreman_products_hashicorp_ubuntu1804:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_ubuntu1804 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 18.04 (Bionic Beaver)"
        label: "{{ foreman_repo_label_prefix | default('') }}azure-cli-ubuntu1804"
        url: "{{ foreman_repo_baseurl_Hashicorp }}/repos/azure-cli/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_ubuntu1804 }}"
        deb_releases: bionic

foreman_products_hashicorp_ubuntu2004:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_ubuntu2004 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 20.04 (Focal Fossa)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-ubuntu2004"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_ubuntu2004 }}"
        deb_releases: focal

foreman_products_hashicorp_ubuntu2204:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_ubuntu2204 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 22.04 (Jammy Jellyfish)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-ubuntu2204"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_ubuntu2204 }}"
        deb_releases: jammy

foreman_products_hashicorp_ubuntu2404:
  - name: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    label: "{{ foreman_product_label_prefix | default('') }}Hashicorp"
    organization: "{{ foreman_organization_hashicorp_ubuntu2404 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 24.04 (Noble Numbat)"
        label: "{{ foreman_repo_label_prefix | default('') }}hashicorp-ubuntu2404"
        url: "{{ foreman_repo_baseurl_hashicorp_apt }}/"
        <<: *foreman_products_defaults_debian
        organization: "{{ foreman_organization_hashicorp_ubuntu2404 }}"
        deb_releases: noble


foreman_content_views_hashicorp_el7:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_el7"
    organization: "{{ foreman_organization_hashicorp_el7 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - RHEL 7"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_el7 }}"

foreman_content_views_hashicorp_el8:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_el8"
    organization: "{{ foreman_organization_hashicorp_el8 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - RHEL 8"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_el8 }}"

foreman_content_views_hashicorp_el9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_el9"
    organization: "{{ foreman_organization_hashicorp_el9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - RHEL 9"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_el9 }}"


foreman_content_views_hashicorp_fedora37:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_fedora37"
    organization: "{{ foreman_organization_hashicorp_fedora37 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - Fedora 37"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_fedora37 }}"

foreman_content_views_hashicorp_fedora38:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_fedora38"
    organization: "{{ foreman_organization_hashicorp_fedora38 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - Fedora 38"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_fedora38 }}"

foreman_content_views_hashicorp_fedora39:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_fedora39"
    organization: "{{ foreman_organization_hashicorp_fedora39 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - x86_64 - Fedora 39"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_fedora39 }}"


foreman_content_views_hashicorp_debian9:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_debian9"
    organization: "{{ foreman_organization_hashicorp_debian9 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 9 (Stretch)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_debian9 }}"

foreman_content_views_hashicorp_debian10:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_debian10"
    organization: "{{ foreman_organization_hashicorp_debian10 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 10 (Buster)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_debian10 }}"

foreman_content_views_hashicorp_debian11:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_debian11"
    organization: "{{ foreman_organization_hashicorp_debian11 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 11 (Bullseye)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_debian11 }}"

foreman_content_views_hashicorp_debian12:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_debian12"
    organization: "{{ foreman_organization_hashicorp_debian12 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Debian 12 (Bookworm)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_debian12 }}"


foreman_content_views_hashicorp_ubuntu1804:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_ubuntu1804"
    organization: "{{ foreman_organization_hashicorp_ubuntu1804 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 18.04 (Bionic Beaver)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_ubuntu1804 }}"

foreman_content_views_hashicorp_ubuntu2004:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_ubuntu2004"
    organization: "{{ foreman_organization_hashicorp_ubuntu2004 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 20.04 (Focal Fossa)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_ubuntu2004 }}"

foreman_content_views_hashicorp_ubuntu2204:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_ubuntu2204"
    organization: "{{ foreman_organization_hashicorp_ubuntu2204 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 22.04 (Jammy Jellyfish)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_ubuntu2204 }}"

foreman_content_views_hashicorp_ubuntu2404:
  - name: "{{ foreman_cv_prefix | default('cv_') }}{{ foreman_cv_name_prefix | default('') }}hashicorp_ubuntu2404"
    organization: "{{ foreman_organization_hashicorp_ubuntu2404 }}"
    repositories:
      - name: "{{ foreman_repo_name_prefix | default('') }}Hashicorp Stable - Amd64 - Ubuntu 24.04 (Noble Numbat)"
        product: "{{ foreman_product_name_prefix | default('') }}Hashicorp"
    allow_promote: "{{ foreman_cv_allow_promote_hashicorp_ubuntu2404 }}"

